/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_hocsinh;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author AnhQuoc
 */
public class TDQuyDinh extends javax.swing.JInternalFrame implements ActionListener{

    /**
     * Creates new form TDQuyDinh
     */
    public TDQuyDinh() {
        initComponents();
        jbtnss.addActionListener(this);
        jbtnmh.addActionListener(this);
        jbtndt.addActionListener(this);
        jbtndd.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnss = new javax.swing.JButton();
        jbtnmh = new javax.swing.JButton();
        jbtndt = new javax.swing.JButton();
        jbtndd = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Thay đổi quy định");

        jbtnss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnss.setText("Thay đổi sỉ số");
        jbtnss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnssActionPerformed(evt);
            }
        });

        jbtnmh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnmh.setText("Thay đổi môn học");

        jbtndt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtndt.setText("Thay đổi độ tuổi");

        jbtndd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtndd.setText("Thay đổi điểm đạt");
        jbtndd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnss, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtndd)
                    .addComponent(jbtnmh))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnss, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnmh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtndd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnssActionPerformed

    private void jbtnddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtndd;
    private javax.swing.JButton jbtndt;
    private javax.swing.JButton jbtnmh;
    private javax.swing.JButton jbtnss;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(jbtnss)){
            jbtnssclick();
        }
        else if (e.getSource().equals(jbtnmh)){
            jbtnmhclick();
        }
        else if (e.getSource().equals(jbtndt)){
            jbtndtclick();
        }
        else{
            jbtnddclick();
        }
        //To change body of generated methods, choose Tools | Templates.
    }
    
    public void jbtnssclick(){
        new Thaydoisiso().setVisible(true);
    }
    
    public void jbtnmhclick(){
        new Thaydoimonhoc().setVisible(true);
    }
    
    public void jbtndtclick(){
        new Thaydoidotuoi().setVisible(true);
    }
    
    public void jbtnddclick(){
        new Thaydoidiemdat().setVisible(true);
    }
}
