/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_hocsinh;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUYNH MINH
 */
public class Tongketmon extends javax.swing.JFrame {
    DbConnect con;
    /**
     * Creates new form Tongketmon
     */
    public Tongketmon() {
        initComponents();
        con = new DbConnect();
        LoadDataCB();
        showData();
        ShowTT();
        jTextField_tenmh.setEnabled(false);
    }
    
    public void LoadDataCB(){
        try{
            ResultSet rs = con.getData("SELECT * FROM MONHOC");
            ResultSet rss = con.getData("SELECT * FROM LOP");
            while (rs.next()){
                this.jComboBox_mon.addItem(rs.getString("MAMH"));
            }
            while (rss.next()){
                this.jComboBox_lop.addItem(rss.getString("MALOP"));
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e, "Thông báo lỗi",1);
        }
    }
    
    public void LoadTen(){
        try {
                ResultSet rs = con.getData("SELECT Ten FROM MONHOC WHERE MAMH like N'%" + jComboBox_mon.getSelectedItem().toString() + "%'");
                while (rs.next()){
                    jTextField_tenmh.setText(rs.getString("Ten"));
                }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Thông báo lỗi",1);
        }
    }
    
    public void showData (){
        String[] columnNames = {"Lớp","Sỉ số","Số lượng đạt","Tỉ lệ %"};
        DefaultTableModel model = new DefaultTableModel();
        
        model.setColumnIdentifiers(columnNames);
        jTable1.setModel(model);
        
        String Lop ="";
        String SS ="";
        String SL = "";
        String TL = "";
        
        ResultSet rs = con.getData("select L.MALOP, L.SL, \n" +
"[Dat] = (select count(D.MAHS) from DIEMKIEMTRA D, DIEMDATMON DD, CTLOP C where D.MAMH = DD.MAMH and D.MAHS = C.MAHS and D.DTBM>= DD.DiemDat  and D.MAMH like '%"+jComboBox_mon.getSelectedItem().toString()+"%' and C.MALOP like '%"+jComboBox_lop.getSelectedItem()+"%'),\n" +
"[TL] = convert(varchar(50),((select count(D.MAHS) from DIEMKIEMTRA D, DIEMDATMON DD, CTLOP C where D.MAMH = DD.MAMH and D.MAHS = C.MAHS and D.DTBM>= DD.DiemDat and D.MAMH like '%"+jComboBox_mon.getSelectedItem().toString()+"%' and C.MALOP like '%"+jComboBox_lop.getSelectedItem()+"%') / convert(float,L.SL)*100)) + '%'\n" +
"from LOP L, DIEMKIEMTRA D, CTLOP C\n" +
"where L.MALOP = C.MALOP and C.MAHS = D.MAHS and C.MALOP like '%"+jComboBox_lop.getSelectedItem()+"%'\n" +
"group by L.MALOP, L.SL");   
        try {
            while (rs.next()){
                Lop = rs.getString("MALOP");
                SS = rs.getString("SL");
                SL = rs.getString("Dat");
                TL = rs.getString("TL");
                
                model.addRow(new Object[] {Lop,SS,SL,TL});
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainTheme.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    
    public void ShowTT (){
        jLabel_tt.setText("Lớp đang chọn là: "+jComboBox_lop.getSelectedItem().toString()+"!");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_mon = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_tt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_lop = new javax.swing.JComboBox<>();
        jTextField_tenmh = new javax.swing.JTextField();

        setTitle("Tổng kết môn");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tổng kết môn");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Môn");

        jComboBox_mon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_mon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_monItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lớp", "Sỉ số", "Số lượng đạt", "Tỉ lệ"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel_tt.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel_tt.setText("jLabel5");

        jLabel2.setText("Lớp");

        jComboBox_lop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_lopItemStateChanged(evt);
            }
        });
        jComboBox_lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_lopMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_tt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(146, 146, 146))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_lop, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField_tenmh, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_tenmh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_tt)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_monItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_monItemStateChanged
        // TODO add your handling code here:
        showData();
        LoadTen();
    }//GEN-LAST:event_jComboBox_monItemStateChanged

    private void jComboBox_lopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_lopMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_lopMouseClicked

    private void jComboBox_lopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_lopItemStateChanged
        // TODO add your handling code here:
        ShowTT();
    }//GEN-LAST:event_jComboBox_lopItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tongketmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tongketmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tongketmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tongketmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tongketmon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_lop;
    private javax.swing.JComboBox<String> jComboBox_mon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_tt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_tenmh;
    // End of variables declaration//GEN-END:variables
}
