USE [QL_HOCSINH]
GO

INSERT INTO [dbo].[HT_KIEMTRA] (MAKT,Ten) VALUES ('KT15',N'Kiểm tra 15 phút')
GO

INSERT INTO [dbo].[HT_KIEMTRA] (MAKT,Ten) VALUES ('KT45',N'Kiểm tra 45 phút')
GO

SELECT * FROM HT_KIEMTRA