USE [QL_HOCSINH]
GO

INSERT INTO [dbo].[LOP] (MALOP,MAKHOI) VALUES ('10A1','K10')
GO

INSERT INTO [dbo].[LOP] (MALOP,MAKHOI) VALUES ('10A2','K10')
GO

INSERT INTO [dbo].[LOP] (MALOP,MAKHOI) VALUES ('10A3','K10')
GO

INSERT INTO [dbo].[LOP] (MALOP,MAKHOI) VALUES ('10A4','K10')
GO

INSERT INTO [dbo].[LOP] (MALOP,MAKHOI) VALUES ('11A1','K11')
GO

INSERT INTO [dbo].[LOP] (MALOP,MAKHOI) VALUES ('11A2','K11')
GO

INSERT INTO [dbo].[LOP] (MALOP,MAKHOI) VALUES ('11A3','K11')
GO

INSERT INTO [dbo].[LOP] (MALOP,MAKHOI) VALUES ('12A1','K12')
GO

INSERT INTO [dbo].[LOP] (MALOP,MAKHOI) VALUES ('12A2','K12')
GO

SELECT * FROM LOP